"""
Ask the Doc Application - Week 15 LangChain Lab
===============================================
This Streamlit app allows users to ask questions about uploaded text documents
using LangChain's question-answering chain with OpenAI embeddings and Chroma vector store.

Author: Programming for Analytics Student
Date: 2026
"""

import streamlit as st
from langchain_openai import OpenAI
from langchain.text_splitter import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma
from langchain.chains import RetrievalQA


def generate_response(uploaded_file, openai_api_key, query_text):
    """
    Generate an answer to a question about the uploaded document.

    Args:
        uploaded_file: Text file uploaded by user
        openai_api_key: OpenAI API key for authentication
        query_text: Question to ask about the document

    Returns:
        Answer generated by the LLM based on document context
    """

    # Load document if file is uploaded
    if uploaded_file is not None:
        document = uploaded_file.read().decode('utf-8')

    # Split documents into chunks (small pieces for better retrieval)
    text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
    texts = text_splitter.split_text(document)

    # Select embeddings (converts text to numerical vectors)
    embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)

    # Create a vectorstore from documents (Chroma is an embedding database)
    db = Chroma.from_texts(texts, embeddings)

    # Create retriever interface (searches for relevant document chunks)
    retriever = db.as_retriever()

    # Create QA chain (combines retriever with LLM for question answering)
    qa = RetrievalQA.from_chain_type(
        llm=OpenAI(openai_api_key=openai_api_key),
        chain_type='stuff',
        retriever=retriever
    )

    # Run the chain and get the response
    response = qa.run(query_text)
    return response


# ============================================================================
# STREAMLIT APP FRONTEND
# ============================================================================

# Page title
st.set_page_config(page_title='🦜🔗 Ask the Doc')
st.title('🦜🔗 Ask the Doc')
st.subheader('Ask questions about your documents using AI')

# File upload widget
uploaded_file = st.file_uploader('Upload a text document (.txt)', type='txt')

# Query text input (disabled until file is uploaded)
query_text = st.text_input(
    'Enter your question:',
    placeholder='What is this document about?',
    disabled=not uploaded_file
)

# Form for input submission
result = []
with st.form('myform', clear_on_submit=True):
    # OpenAI API key input
    openai_api_key = st.text_input(
        'Enter your OpenAI API key:',
        type='password',
        placeholder='sk-...',
        disabled=not (uploaded_file and query_text)
    )

    # Submit button
    submitted = st.form_submit_button(
        'Submit',
        disabled=not (uploaded_file and query_text and openai_api_key)
    )

    if submitted:
        with st.spinner('🔄 Processing your question...'):
            response = generate_response(uploaded_file, openai_api_key, query_text)
            result.append(response)

# Display the result if available
if len(result):
    st.success('✅ Answer generated!')
    st.write(result[0])
    st.info('💡 Tip: The API key is not stored. Upload a new document to ask another question.')